### ISSUE TITLE
Upgrading from AppWeb 2.4 to AppWeb 4.7.1 or newer

### ISSUE THREAD

**Issue by M5Mathieu** [embedthis/appweb#465]
We have an old Appweb and we want to update it to a modern appweb.

We firstly tried appweb to built version 5.4.0 and had quite a few issues cross-compiling with me, and generally building. So instead we went to the long time support version 4.7.1.

MakeMe didn't work, and didn't cross-compile. It only wanted to use the local build tool, building for the local system, and outright didn't want to build for ppc, or even try.

Using make and strongly changing the makefile so it could build static libs, with specified php, curl and openssl, we managed to build it. Finally!

But Esp changed. From embedded JavaScript to embedded C... A complete change. Ejs seemed to be the new Esp. So we tried to built it. And we got problems : ejs.mod need to be compiled. With ejsc, that we just compiled with non native cpu, so it's not executing... Running the compilation is not a possibility. The system just does have any horse power to do actual compiling.

We are looking for way to not have to remake the web pages, but get access to the new features. So we want to be backward compatible on the esp pages and able to cross-compile. We can change the code, it not an issue, at least if we can still have the host and the session. Can it be done?

**Comment by embedthis** [comment]
Appweb 4.7 will soon be retired. It is supported till the end of the year, but you are strongly encouraged to use 5.4. You will save time in the long run.

Our recommended way of building is MakeMe. Using Make and providing flexibility with configuration is horrible. Autoconf, configure + Make is just a mess. That is why we use MakeMe. It looks after most issues of cross compilation for you. It will also generate Makefiles if required.

There is a lot of doc about cross compiling at: http://embedthis.com/makeme/doc/users/cross.html

The supplied Makefiles are pretty hard coded. Make is a bear to manage cross compiling so we recommend not to use it, unless you want to create your own custom Makefiles. Then, use the supplied Makefiles under projects and customize as you have done.

Regarding ESP. The old ESP in Appweb 2 was a tiny, Javascript like expression parser. It was slow and you had to create javascript functions for your C code. The new ESP embeds real "C" code. It runs 100x faster and provide much more capabilities. Migrating Appweb 2 ESP to Appweb 5 ESP will take editing because ESP is now C.

Ejscript is a full Javascript environment, but not as good for embedding because it is much larger. 

Yes, many, many users have migrated up to Appweb 5. Definitely worthwhile and doable.

**Comment by M5Mathieu** [comment]
Thanks for the answer. 

Unfortunately, makeMe doesn't seam to be able to cross-compile to ppc. Unknown arch type. 

Using the make file works perfectly... 

However, trying to create a make file with make doesn't seem to work. Calling -gen make does not seem to generate any files in the folder sub-tree. More over, it didn't want to use openssl, even though to path to it was specified with --with openssl=${openssl_path}
with ${openssl_path} pointing to a lib and include dir.

**Comment by embedthis** [comment]
Fix for makeme for ppc just posted.
Projects are generated under a projects directory. E.g.
```
me -d -q -platform macosx-x64-mine -configure . -with openssl -gen make
```
Install openssl via:

```
pak install "openssl#1.0.2a"
```

**Comment by M5Mathieu** [comment]
Ok, thank you!

**Comment by karthikCig** [comment]
Trying to upgrade Appweb 3.2 to Appweb 4.7.3. Need to known some clarification about 'Ejscript module' compatibility before we go to Appweb 4.7.

Already we have an 'Application' which developed useing Ejscript of Appweb 3.2 framework(Ejs 1.x).Currently Application is running on Embedded machine.

I observed that Appweb 4.7.3 uses Ejscript Framework 2.X ,so if we upgrade it to Appweb 4.7, weather the Applications which developed using old EJS framework are still compatible with Appweb 4.7 or not.

Can you please let us know about EJS compatibility.

**Comment by embedthis** [comment]
Why upgrade to Appweb 4.7, that version is deprecated and no longer supported.
