### ISSUE TITLE
Cannot find view?

### ISSUE THREAD

**Issue by Waching** [embedthis/appweb#467]
# Environment
Appweb version: 4.7.1
O/S: Linux 
CPU: arm
# Problem Description:
I updated appweb to 4.7.1, but my controller program cannot work as 4.3.4. When I run esp controller it always report cannot find view:
`appweb: Error: Cannot find module "cache/view_c70f99d2390ad91bffb40f4fb3b393e1.so"`
and 
`appweb: 2: Error: Cannot find view`
I hadn't built any view and I don't know why it always to find view_c70f99d2390ad91bffb40f4fb3b393e1.so.
How can I remove the view_c70f99d2390ad91bffb40f4fb3b393e1.so?
# appweb.conf:
`ErrorLog "stdout" level=2`
`LoadModule espHandler libmod_esp`
`LoadModule sslModule libmod_ssl`
`Listen 80`
`AddOutputFilter chunkFilter`
`AddHandler espHandler esp`
`AddHandler fileHandler ""`
`SSLCertificateFile "self.crt"`
`SSLCertificateKeyFile "self.key"`
`<Route /tt/>`
`    AddHandler espHandler`
`    Source     controllers/controller.c`
`    Target     run request-tt`
`</Route>`
`<Route /ws/tt/{action}$>`
`    ResetPipeline`
`    Prefix                  /ws`
`    AddFilter               webSocketFilter`
`    AddHandler              espHandler`
`    Documents      `
`    Source                  controllers/controller.c`
`    Target                  run tt-$1`
`    RequestTimeout          2hrs`
`    InactivityTimeout       10mins`
`    WebSocketsPing          5mins`
`    WebSocketsProtocol      chat`
`</Route>`
`EspUpdate off`
`EspKeepSource       off`

**Comment by embedthis** [comment]
Capture the appweb log trace output at level 4. You will see what request is being translated into a request for a view. If a request is sent to ESP and there is not controller, it will try to find an ESP page for that request. Because you have EspUpdate off, ESP expects you to have pre-supplied compiled pages for all possible requests. If there is not an ESP page (view) for the request, you will get a 404 response and the message you see.

**Comment by Waching** [comment]
Thank you, I've found the root case and fixed this issue according to your information.
