### ISSUE TITLE
Ejscript compatability: Upgrade to Appweb 4.7.3 from Appweb 3.2

### ISSUE THREAD

**Issue by karthikCig** [embedthis/appweb#492]
Trying to upgrade Appweb 3.2 to Appweb 4.7.3. Need to known some clarification about 'Ejscript module' compatibility before we go to Appweb 4.7.

Already we have an 'Application' which developed useing Ejscript of Appweb 3.2 framework(Ejs 1.x).Currently Application is running on Embedded machine.

I observed that Appweb 4.7.3 uses Ejscript Framework 2.X ,so if we upgrade it to Appweb 4.7, weather the Applications which developed using old EJS framework are still compatible with Appweb 4.7 or not.

Can you please let us know about EJS compatibility.

**Comment by embedthis** [comment]
You should upgrade to Appweb 5 or 6. Appweb 4 is being retired.

The ejscript in Appweb 4+ is greatly enhanced from that in Appweb 3, so you will have some upgrading to do. In Appweb 4, ejscript was split two ways:

1. Ejscript itself got much more capable. This meant it got bigger.

2. ESP implemented the same embedded syntax as Ejscript, but uses embedded C code. So it is much smaller and faster.

We found that Ejscript 1.x was not doing much more than embedded C code could do. It was difficult to bind C functions to Ejscript functions. So ESP makes this much easier. Similarly, Ejscript 2 is more powerful so that you don't need to bind C functions as much.

Our recommendation is to migrate Ejscript 1.X applications to use ESP where ever possible. It will give you a faster, more compact result.
