### ISSUE TITLE
any benchmark against nginx?

### ISSUE THREAD

**Issue by superdolt** [embedthis/appweb#660]
any benchmark against nginx?

what's the max concurrent connection and max conncurrent connection memory use? (memory per connection)

**Comment by mobsense** [comment]
Sorry, no. Because it isn't really relevant.

nginx is a scalable enterprise web server designed for maximum throughput in a fairly unconstrained memory / CPU environment. 

Appweb is designed for predictable throughput in a very constrained environment. Appweb will do 10K requests per second, but it depends on the requests and CPU so benchmarks are not really indicative.

Appweb should run with SSL in 2-4MB of RAM. With a well designed App, the entire footprint should be < 5MB. 

Appweb has extensive security defensive countermeasures and limits to detect excessive load or hacker attacks. 

So Appweb and Nginx have different goals.

I'd recommend you look closely at the feature set and the environment you want to use it in.

**Comment by mobsense** [comment]
But I should also add. Appweb will have ample throughput and performance for nearly every application. It has been extensively tuned and optimized over the years.
